project_id = "errzsskktbinjzryecsg"
 
 [functions.geocode-location]
 verify_jwt = false
 
 [functions.search-local-info]
 verify_jwt = false
 
 [functions.import-localities]
 verify_jwt = false
 
 [functions.verify-admin]
 verify_jwt = false